import { ref, reactive } from 'vue'
import { defineStore } from 'pinia'
import dayjs from 'dayjs'
export const useAssistant = defineStore('assistant', () => {
	const textScript = reactive([
		// 	// { content: '<span>我想知道台北市哪裡較常發生交通事故</span>', time: dayjs(new Date()).format('HH:mm') },
		// 	// { content: '<div style="display: flex; gap:2px;">目前以強盜、搶奪、汽機車竊盜和住宅竊盜次數等分析結果來看，</div><div style="margin-top: 5px;display: flex; gap: 9px; cursor: pointer; align-items: center;"><span style="color: #9E8EFF; font-weight: 700; font-size: 14px;" >查看圖表</span><span style="color: #9E8EFF; font-weight: 700; font-size: 14px;" >匯入列表中查看</span></div>', time: dayjs(new Date()).format('HH:mm') },
		// 	// { content: '<span>我想知道台北市哪裡是犯罪熱區</span>', time: '12:34' },
		// 	// { content: '<div style="display: flex; gap:2px;">目前台北市共有130間派出所</div><div style="margin-top: 5px;display: flex; gap: 9px; cursor: pointer; align-items: center;"><span style="color: #9E8EFF; font-weight: 700; font-size: 14px;" >查看圖表</span></div>', time: '12:35' },
		// 	// { content: '<span>我想知道台北市哪裡是犯罪熱區</span>', time: '12:34' },
		// 	// { content: '<div style="display: flex; gap:2px;">目前台北市共有130間派出所</div><div style="margin-top: 5px;display: flex; gap: 9px; cursor: pointer; align-items: center;"><span style="color: #9E8EFF; font-weight: 700; font-size: 14px;" >查看圖表</span></div>', time: '12:35' },
		// 	// { content: '<span>我想知道台北市哪裡是犯罪熱區</span>', time: '12:34' },
		// 	// { content: '<div style="display: flex; gap:2px;">目前台北市共有130間派出所</div><div style="margin-top: 5px;display: flex; gap: 9px; cursor: pointer; align-items: center;"><span style="color: #9E8EFF; font-weight: 700; font-size: 14px;" >查看圖表</span></div>', time: '12:35' },
	])
	const responseData = ref(
		{
			threshold: 17,
			question: '如果我要搭公車到市政府，哪些是我可以為了節能減碳做的?',
			scores: [
				{ tag_name: "人均減碳", score: 8 },
				{ tag_name: "碳排放", score: 8 },
				{ tag_name: "能源消耗", score: 9 },
				{ tag_name: "環保政策", score: 6 },
				{ tag_name: "節能減碳", score: 2 },
				{ tag_name: "溫室氣體", score: 11 },
				{ tag_name: "氣候變遷", score: 4 },
				{ tag_name: "環境永續", score: 17 },
				{ tag_name: "二氧化碳當量", score: 1 },
				{ tag_name: "減碳管理", score: 19 },
				{ tag_name: "能源效率", score: 9 },
				{ tag_name: "刑事統計", score: 18 },
				{ tag_name: "犯罪率", score: 18 },
				{ tag_name: "治安維護", score: 7 },
				{ tag_name: "罪案類型", score: 3 },
				{ tag_name: "地區熱點", score: 3 },
				{ tag_name: "破案率", score: 18 },
				{ tag_name: "警力資源", score: 10 },
				{ tag_name: "預防犯罪", score: 4 },
				{ tag_name: "社區安全", score: 18 },
				{ tag_name: "資料分析", score: 16 },
				{ tag_name: "政策規劃", score: 0 },
				{ tag_name: "台北市各區即時空氣品質", score: 15 },
				{ tag_name: "空氣污染", score: 8 },
				{ tag_name: "PM2.5濃度", score: 1 },
				{ tag_name: "環境監測", score: 5 },
				{ tag_name: "健康風險", score: 4 },
				{ tag_name: "污染來源", score: 8 },
				{ tag_name: "敏感區域", score: 6 },
				{ tag_name: "揚塵管控", score: 10 },
				{ tag_name: "空品預警", score: 8 },
				{ tag_name: "民生品質", score: 9 },
				{ tag_name: "永續城市", score: 18 },
				{ tag_name: "抽水站狀態", score: 15 },
				{ tag_name: "防災應變", score: 12 },
				{ tag_name: "水利設施", score: 0 },
				{ tag_name: "抽水站運作", score: 14 },
				{ tag_name: "水位監控", score: 13 },
				{ tag_name: "排水系統", score: 15 },
				{ tag_name: "防汛整備", score: 19 },
				{ tag_name: "易淹水區域", score: 7 },
				{ tag_name: "雨災風險", score: 9 },
				{ tag_name: "基礎建設", score: 18 },
				{ tag_name: "緊急應變", score: 1 },
				{ tag_name: "社福人口", score: 8 },
				{ tag_name: "低收入戶", score: 16 },
				{ tag_name: "身心障礙", score: 8 },
				{ tag_name: "弱勢關懷", score: 9 },
				{ tag_name: "社會資源", score: 4 },
				{ tag_name: "生活補助", score: 15 },
				{ tag_name: "福利政策", score: 11 },
				{ tag_name: "人口統計", score: 11 },
				{ tag_nam: "經濟狀況", score: 18 },
				{ tag_nam: "社會公平", score: 6 },
				{ tag_name: "風險評估", score: 5 },
				{ tag_name: "社福機構", score: 9 },
				{ tag_name: "社會服務", score: 2 },
				{ tag_name: "機構分布", score: 1 },
				{ tag_name: "弱勢族群", score: 5 },
				{ tag_name: "服務資源", score: 7 },
				{ tag_name: "社區照顧", score: 18 },
				{ tag_name: "長期照護", score: 17 },
				{ tag_name: "兒少保護", score: 8 },
				{ tag_name: "婦女權益", score: 7 },
				{ tag_name: "專業輔導", score: 3 },
				{ tag_name: "民間組織", score: 1 },
				{ tag_name: "綠電發電量", score: 2 },
				{ tag_name: "再生能源", score: 7 },
				{ tag_name: "發電量", score: 1 },
				{ tag_name: "能源結構", score: 9 },
				{ tag_name: "環境保護", score: 4 },
				{ tag_name: "碳中和", score: 17 },
				{ tag_name: "能源轉型", score: 1 },
				{ tag_name: "綠能政策", score: 2 },
				{ tag_name: "發電效率", score: 16 },
				{ tag_name: "減碳目標", score: 6 },
				{ tag_name: "科技創新", score: 12 },
				{ tag_name: "資源站可回收項目", score: 17 },
				{ tag_name: "資源回收", score: 5 },
				{ tag_name: "廢棄物處理", score: 16 },
				{ tag_name: "環保意識", score: 4 },
				{ tag_name: "循環經濟", score: 19 },
				{ tag_name: "垃圾分類", score: 7 },
				{ tag_name: "資源再利用", score: 15 },
				{ tag_name: "減廢政策", score: 13 },
				{ tag_name: "回收率", score: 18 },
				{ tag_name: "環境教育", score: 13 },
				{ tag_name: "永續發展", score: 5 },
				{ tag_name: "閒置市有財產", score: 17 },
				{ tag_name: "公有地", score: 16 },
				{ tag_name: "閒置資產", score: 7 },
				{ tag_name: "資產管理", score: 11 },
				{ tag_name: "土地利用", score: 0 },
				{ tag_name: "都市規劃", score: 12 },
				{ tag_name: "地政", score: 7 },
				{ tag_name: "土地徵收", score: 18 },
				{ tag_name: "興辦事業", score: 10 },
				{ tag_name: "場所再利用", score: 14 },
				{ tag_name: "市地重劃", score: 14 }
			]
		})
	return {
		textScript, responseData
	}
})
